-- Add fields to whatsapp_messages table for AI automation tracking
-- Run this migration in your Supabase SQL Editor

-- Add is_ai_response field to tag AI-generated responses
ALTER TABLE whatsapp_messages 
ADD COLUMN IF NOT EXISTS is_ai_response BOOLEAN DEFAULT FALSE;

-- Add needs_agent_review field to flag messages that need human attention
ALTER TABLE whatsapp_messages 
ADD COLUMN IF NOT EXISTS needs_agent_review BOOLEAN DEFAULT FALSE;

-- Add auto_reply_status field to track auto-reply state
-- Values: 'auto_replied' (auto-reply was sent), 'flagged_for_agent' (needs review), 'manual_only' (skip auto-reply), NULL (not processed yet)
ALTER TABLE whatsapp_messages 
ADD COLUMN IF NOT EXISTS auto_reply_status TEXT;

-- Add index for efficient querying of flagged messages
CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_needs_review 
ON whatsapp_messages(needs_agent_review) 
WHERE needs_agent_review = TRUE;

-- Add index for AI responses
CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_ai_response 
ON whatsapp_messages(is_ai_response) 
WHERE is_ai_response = TRUE;

-- Add index for auto_reply_status
CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_auto_reply_status 
ON whatsapp_messages(auto_reply_status);

-- Add comment for documentation
COMMENT ON COLUMN whatsapp_messages.is_ai_response IS 'True if this message was generated by AI';
COMMENT ON COLUMN whatsapp_messages.needs_agent_review IS 'True if this message needs human agent review';
COMMENT ON COLUMN whatsapp_messages.auto_reply_status IS 'Status of auto-reply: auto_replied, flagged_for_agent, manual_only, or NULL';

